# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/beevik/ntp"
  version = "0.2.0"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "17.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/ema/qdisc"

[[constraint]]
  name = "github.com/godbus/dbus"
  version = "4.1.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/kolo/xmlrpc"

[[constraint]]
  branch = "master"
  name = "github.com/lufia/iostat"

[[constraint]]
  branch = "master"
  name = "github.com/mdlayher/wifi"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_model"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/prometheus/node_exporter"
  version = "0.15.2"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/procfs"

[[constraint]]
  branch = "master"
  name = "github.com/soundcloud/go-runit"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[prune]
  go-tests = true
  unused-packages = true
